export const CONTRACT_ADDRESS = "0x8D5BC8c59758431DDdaCf6B9D122bAFCBEf87cDF";

export const CONTRACT_ABI = [
  "function addIssuer(address _issuer) external",
  "function removeIssuer(address _issuer) external",
  "function setPaused(bool _state) external",
  "function setRequiredApprovals(uint256 _required) external",
  "function proposeBatch(string calldata _batchId, bytes32 _merkleRoot) external returns (uint256)",
  "function approveBatch(uint256 _proposalId) external",
  "function revokeBatch(string calldata _batchId, string calldata _reason) external",
  "function revokeCertificate(bytes32 _certHash, string calldata _reason) external",
  "function verifyCertificate(string calldata _batchId, bytes32 _certHash) external view returns (bool valid, bool revoked, string memory reason, bytes32 merkleRoot, uint256 issuedAt, address issuedBy)",
  "function getBatch(string calldata _batchId) external view returns (tuple(bytes32 merkleRoot, uint256 issuedAt, address issuedBy, bool isRevoked, string revokeReason))",
  "function getProposal(uint256 _proposalId) external view returns (string memory batchId, bytes32 merkleRoot, address proposedBy, uint256 approvalCount, bool executed)",
  "function hasApproved(uint256 _proposalId, address _issuer) external view returns (bool)",
  "function isIssuer(address _addr) external view returns (bool)",
  "function owner() external view returns (address)",
  "function totalBatches() external view returns (uint256)",
  "function paused() external view returns (bool)",
  "function requiredApprovals() external view returns (uint256)",
  "function proposalCount() external view returns (uint256)",
  "event BatchIssued(string indexed batchId, bytes32 merkleRoot, address indexed issuedBy, uint256 issuedAt)",
  "event BatchRevoked(string indexed batchId, address revokedBy, string reason, uint256 timestamp)",
  "event CertRevoked(bytes32 indexed certHash, address revokedBy, string reason, uint256 timestamp)",
  "event IssuerAdded(address indexed issuer, address addedBy, uint256 timestamp)",
  "event IssuerRemoved(address indexed issuer, address removedBy, uint256 timestamp)",
  "event BatchProposed(uint256 indexed proposalId, string batchId, bytes32 merkleRoot, address proposedBy)",
  "event BatchApproved(uint256 indexed proposalId, address approvedBy, uint256 approvalCount)",
  "event BatchExecuted(uint256 indexed proposalId, string batchId)"
];